using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Columns;
using System;
using System.ComponentModel;
using DevExpress.Utils;
using DevExpress.XtraGrid.Views.Base;
using System.Drawing;
namespace JHEMR.EMRHisCustom
{
    partial class frmOperationConfirm
    {
        /// <summary>
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows 窗体设计器生成的代码

        /// <summary>
        /// 设计器支持所需的方法 - 不要
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            GridLevelNode gridLevelNode = new GridLevelNode();
            this.panel1 = new Panel();
            this.lblINP_NO = new Label();
            this.txtINP_NO = new TextBox();
            this.txtPatID = new TextBox();
            this.txtName = new TextBox();
            this.lblPATIENT_ID = new Label();
            this.lblName = new Label();
            this.lblPyItemName = new Label();
            this.panelPYInput = new Panel();
            this.gridPYInput = new GridControl();
            this.gridViewPYInput = new GridView();
            this.ITEM_NAME = new GridColumn();
            this.OPERATION_SCALE１ = new GridColumn();
            this.txtInPut = new TextBox();
            this.panel3 = new Panel();
            this.cmbGroup = new System.Windows.Forms.ComboBox();
            this.txtpreq_date_time = new TextBox();
            this.simpleButton4 = new SimpleButton();
            this.sbtnSave = new SimpleButton();
            this.txtoperating_room = new TextBox();
            this.txtfourth_assistant = new TextBox();
            this.txtthird_assistant = new TextBox();
            this.txtsecond_assistant = new TextBox();
            this.txtfirst_assistant = new TextBox();
            this.txtnotes_on_operation = new TextBox();
            this.txtdiag_before_operation = new TextBox();
            this.txtpatient_condition = new TextBox();
            this.txtOPERATING_DEPT = new TextBox();
            this.txtblood_tran_doctor = new TextBox();
            this.txtsequence = new TextBox();
            this.txtentered_by = new TextBox();
            this.txtsurgeon = new TextBox();
            this.cmboperating_room_no = new System.Windows.Forms.ComboBox();
            this.cmboperation_scale = new System.Windows.Forms.ComboBox();
            this.cmbanesthesia_method = new System.Windows.Forms.ComboBox();
            this.cmbisolation_indicator = new System.Windows.Forms.ComboBox();
            this.cmboperating_room = new System.Windows.Forms.ComboBox();
            this.dtpreq_date_time = new DateTimePicker();
            this.dtpscheduled_date_time = new DateTimePicker();
            this.label13 = new Label();
            this.label12 = new Label();
            this.label6 = new Label();
            this.label11 = new Label();
            this.label8 = new Label();
            this.label10 = new Label();
            this.label16 = new Label();
            this.label5 = new Label();
            this.label9 = new Label();
            this.label17 = new Label();
            this.label7 = new Label();
            this.label2 = new Label();
            this.label14 = new Label();
            this.label4 = new Label();
            this.label3 = new Label();
            this.label15 = new Label();
            this.label1 = new Label();
            this.sbtnAdd = new SimpleButton();
            this.sbtnDelete = new SimpleButton();
            this.panel2 = new Panel();
            this.gcOperaion = new GridControl();
            this.gvOperation = new GridView();
            this.OPERATION = new GridColumn();
            this.OPERATION_SCALE = new GridColumn();
            this.statusBottom = new StatusStrip();
            this.tlstatusBottom = new ToolStripStatusLabel();
            this.panel1.SuspendLayout();
            this.panelPYInput.SuspendLayout();
            ((ISupportInitialize)this.gridPYInput).BeginInit();
            ((ISupportInitialize)this.gridViewPYInput).BeginInit();
            this.panel3.SuspendLayout();
            this.panel2.SuspendLayout();
            ((ISupportInitialize)this.gcOperaion).BeginInit();
            ((ISupportInitialize)this.gvOperation).BeginInit();
            this.statusBottom.SuspendLayout();
            base.SuspendLayout();
            this.panel1.Controls.Add(this.lblINP_NO);
            this.panel1.Controls.Add(this.txtINP_NO);
            this.panel1.Controls.Add(this.txtPatID);
            this.panel1.Controls.Add(this.txtName);
            this.panel1.Controls.Add(this.lblPATIENT_ID);
            this.panel1.Controls.Add(this.lblName);
            this.panel1.Controls.Add(this.lblPyItemName);
            this.panel1.Dock = DockStyle.Top;
            this.panel1.Location = new Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(655, 45);
            this.panel1.TabIndex = 0;
            this.lblINP_NO.AutoSize = true;
            this.lblINP_NO.Location = new Point(303, 17);
            this.lblINP_NO.Name = "lblINP_NO";
            this.lblINP_NO.Size = new Size(53, 12);
            this.lblINP_NO.TabIndex = 0;
            this.lblINP_NO.Text = "住院号：";
            this.txtINP_NO.BackColor = Color.WhiteSmoke;
            this.txtINP_NO.Location = new Point(356, 12);
            this.txtINP_NO.Name = "txtINP_NO";
            this.txtINP_NO.ReadOnly = true;
            this.txtINP_NO.Size = new Size(90, 21);
            this.txtINP_NO.TabIndex = 4;
            this.txtPatID.BackColor = Color.WhiteSmoke;
            this.txtPatID.Location = new Point(203, 12);
            this.txtPatID.Name = "txtPatID";
            this.txtPatID.ReadOnly = true;
            this.txtPatID.Size = new Size(90, 21);
            this.txtPatID.TabIndex = 4;
            this.txtName.BackColor = Color.WhiteSmoke;
            this.txtName.Location = new Point(51, 12);
            this.txtName.Name = "txtName";
            this.txtName.ReadOnly = true;
            this.txtName.Size = new Size(90, 21);
            this.txtName.TabIndex = 4;
            this.lblPATIENT_ID.AutoSize = true;
            this.lblPATIENT_ID.Location = new Point(149, 17);
            this.lblPATIENT_ID.Name = "lblPATIENT_ID";
            this.lblPATIENT_ID.Size = new Size(53, 12);
            this.lblPATIENT_ID.TabIndex = 0;
            this.lblPATIENT_ID.Text = "病人ID：";
            this.lblName.AutoSize = true;
            this.lblName.Location = new Point(12, 17);
            this.lblName.Name = "lblName";
            this.lblName.Size = new Size(41, 12);
            this.lblName.TabIndex = 0;
            this.lblName.Text = "姓名：";
            this.lblPyItemName.AutoSize = true;
            this.lblPyItemName.Location = new Point(496, 19);
            this.lblPyItemName.Name = "lblPyItemName";
            this.lblPyItemName.Size = new Size(53, 12);
            this.lblPyItemName.TabIndex = 0;
            this.lblPyItemName.Text = "术前诊断";
            this.lblPyItemName.Visible = false;
            this.panelPYInput.BackColor = SystemColors.ControlLightLight;
            this.panelPYInput.Controls.Add(this.gridPYInput);
            this.panelPYInput.Controls.Add(this.txtInPut);
            this.panelPYInput.Location = new Point(170, 0);
            this.panelPYInput.Name = "panelPYInput";
            this.panelPYInput.Size = new Size(255, 191);
            this.panelPYInput.TabIndex = 5;
            this.panelPYInput.Visible = false;
            this.gridPYInput.EmbeddedNavigator.Name = "";
            gridLevelNode.RelationName = "Level1";
            this.gridPYInput.LevelTree.Nodes.AddRange(new GridLevelNode[]
			{
				gridLevelNode
			});
            this.gridPYInput.Location = new Point(3, 30);
            this.gridPYInput.MainView = this.gridViewPYInput;
            this.gridPYInput.Name = "gridPYInput";
            this.gridPYInput.Size = new Size(215, 153);
            this.gridPYInput.TabIndex = 5;
            this.gridPYInput.ViewCollection.AddRange(new BaseView[]
			{
				this.gridViewPYInput
			});
            this.gridViewPYInput.Columns.AddRange(new GridColumn[]
			{
				this.ITEM_NAME,
				this.OPERATION_SCALE１
			});
            this.gridViewPYInput.GridControl = this.gridPYInput;
            this.gridViewPYInput.Name = "gridViewPYInput";
            this.gridViewPYInput.OptionsView.ColumnAutoWidth = false;
            this.gridViewPYInput.OptionsView.ShowColumnHeaders = false;
            this.gridViewPYInput.OptionsView.ShowGroupPanel = false;
            this.gridViewPYInput.DoubleClick += new EventHandler(this.gridViewPYInput_DoubleClick);
            this.gridViewPYInput.KeyDown += new KeyEventHandler(this.gridViewPYInput_KeyDown);
            this.ITEM_NAME.Caption = "名称";
            this.ITEM_NAME.FieldName = "ITEM_NAME";
            this.ITEM_NAME.Name = "ITEM_NAME";
            this.ITEM_NAME.OptionsColumn.AllowEdit = false;
            this.ITEM_NAME.OptionsColumn.ReadOnly = true;
            this.ITEM_NAME.Visible = true;
            this.ITEM_NAME.VisibleIndex = 0;
            this.ITEM_NAME.Width = 160;
            this.OPERATION_SCALE１.Caption = "等级";
            this.OPERATION_SCALE１.FieldName = "OPERATION_SCALE";
            this.OPERATION_SCALE１.Name = "OPERATION_SCALE１";
            this.txtInPut.Location = new Point(3, 3);
            this.txtInPut.Name = "txtInPut";
            this.txtInPut.Size = new Size(99, 21);
            this.txtInPut.TabIndex = 4;
            this.txtInPut.TextChanged += new EventHandler(this.txtInPut_TextChanged);
            this.txtInPut.KeyDown += new KeyEventHandler(this.txtInPut_KeyDown);
            this.panel3.Controls.Add(this.panelPYInput);
            this.panel3.Controls.Add(this.cmbGroup);
            this.panel3.Controls.Add(this.txtpreq_date_time);
            this.panel3.Controls.Add(this.simpleButton4);
            this.panel3.Controls.Add(this.sbtnSave);
            this.panel3.Controls.Add(this.txtoperating_room);
            this.panel3.Controls.Add(this.txtfourth_assistant);
            this.panel3.Controls.Add(this.txtthird_assistant);
            this.panel3.Controls.Add(this.txtsecond_assistant);
            this.panel3.Controls.Add(this.txtfirst_assistant);
            this.panel3.Controls.Add(this.txtnotes_on_operation);
            this.panel3.Controls.Add(this.txtdiag_before_operation);
            this.panel3.Controls.Add(this.txtpatient_condition);
            this.panel3.Controls.Add(this.txtOPERATING_DEPT);
            this.panel3.Controls.Add(this.txtblood_tran_doctor);
            this.panel3.Controls.Add(this.txtsequence);
            this.panel3.Controls.Add(this.txtentered_by);
            this.panel3.Controls.Add(this.txtsurgeon);
            this.panel3.Controls.Add(this.cmboperating_room_no);
            this.panel3.Controls.Add(this.cmboperation_scale);
            this.panel3.Controls.Add(this.cmbanesthesia_method);
            this.panel3.Controls.Add(this.cmbisolation_indicator);
            this.panel3.Controls.Add(this.cmboperating_room);
            this.panel3.Controls.Add(this.dtpreq_date_time);
            this.panel3.Controls.Add(this.dtpscheduled_date_time);
            this.panel3.Controls.Add(this.label13);
            this.panel3.Controls.Add(this.label12);
            this.panel3.Controls.Add(this.label6);
            this.panel3.Controls.Add(this.label11);
            this.panel3.Controls.Add(this.label8);
            this.panel3.Controls.Add(this.label10);
            this.panel3.Controls.Add(this.label16);
            this.panel3.Controls.Add(this.label5);
            this.panel3.Controls.Add(this.label9);
            this.panel3.Controls.Add(this.label17);
            this.panel3.Controls.Add(this.label7);
            this.panel3.Controls.Add(this.label2);
            this.panel3.Controls.Add(this.label14);
            this.panel3.Controls.Add(this.label4);
            this.panel3.Controls.Add(this.label3);
            this.panel3.Controls.Add(this.label15);
            this.panel3.Controls.Add(this.label1);
            this.panel3.Dock = DockStyle.Fill;
            this.panel3.Location = new Point(0, 145);
            this.panel3.Name = "panel3";
            this.panel3.Size = new Size(655, 340);
            this.panel3.TabIndex = 1;
            this.cmbGroup.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmbGroup.FormattingEnabled = true;
            this.cmbGroup.Items.AddRange(new object[]
			{
				"正常",
				"隔离",
				"放射"
			});
            this.cmbGroup.Location = new Point(200, 95);
            this.cmbGroup.Name = "cmbGroup";
            this.cmbGroup.Size = new Size(93, 20);
            this.cmbGroup.TabIndex = 104;
            this.cmbGroup.SelectedIndexChanged += new EventHandler(this.cmbGroup_SelectedIndexChanged);
            this.txtpreq_date_time.Location = new Point(473, 169);
            this.txtpreq_date_time.Name = "txtpreq_date_time";
            this.txtpreq_date_time.ReadOnly = true;
            this.txtpreq_date_time.Size = new Size(123, 21);
            this.txtpreq_date_time.TabIndex = 103;
            this.simpleButton4.Location = new Point(542, 272);
            this.simpleButton4.Name = "simpleButton4";
            this.simpleButton4.Size = new Size(75, 23);
            this.simpleButton4.TabIndex = 102;
            this.simpleButton4.Text = "关闭(&C)";
            this.simpleButton4.Click += new EventHandler(this.simpleButton4_Click_1);
            this.sbtnSave.Location = new Point(433, 272);
            this.sbtnSave.Name = "sbtnSave";
            this.sbtnSave.Size = new Size(75, 23);
            this.sbtnSave.TabIndex = 101;
            this.sbtnSave.Text = "保存(&S)";
            this.sbtnSave.Click += new EventHandler(this.sbtnSave_Click);
            this.txtoperating_room.BackColor = Color.OldLace;
            this.txtoperating_room.Location = new Point(291, 58);
            this.txtoperating_room.Name = "txtoperating_room";
            this.txtoperating_room.Size = new Size(98, 21);
            this.txtoperating_room.TabIndex = 7;
            this.txtoperating_room.TextChanged += new EventHandler(this.txtoperating_room_TextChanged);
            this.txtoperating_room.KeyDown += new KeyEventHandler(this.txtOPERATING_DEPT_KeyDown);
            this.txtoperating_room.Leave += new EventHandler(this.txtOPERATING_DEPT_Leave);
            this.txtoperating_room.KeyPress += new KeyPressEventHandler(this.txtOPERATING_DEPT_KeyPress);
            this.txtoperating_room.Enter += new EventHandler(this.txtOPERATING_DEPT_Enter);
            this.txtfourth_assistant.BackColor = Color.OldLace;
            this.txtfourth_assistant.Location = new Point(513, 130);
            this.txtfourth_assistant.MaxLength = 8;
            this.txtfourth_assistant.Name = "txtfourth_assistant";
            this.txtfourth_assistant.Size = new Size(83, 21);
            this.txtfourth_assistant.TabIndex = 17;
            this.txtfourth_assistant.KeyDown += new KeyEventHandler(this.txtsurgeon_KeyDown);
            this.txtfourth_assistant.Leave += new EventHandler(this.txtsurgeon_Leave);
            this.txtfourth_assistant.KeyPress += new KeyPressEventHandler(this.txtsurgeon_KeyPress);
            this.txtfourth_assistant.Enter += new EventHandler(this.txtsurgeon_Enter);
            this.txtthird_assistant.BackColor = Color.OldLace;
            this.txtthird_assistant.Location = new Point(422, 130);
            this.txtthird_assistant.MaxLength = 8;
            this.txtthird_assistant.Name = "txtthird_assistant";
            this.txtthird_assistant.Size = new Size(87, 21);
            this.txtthird_assistant.TabIndex = 16;
            this.txtthird_assistant.KeyDown += new KeyEventHandler(this.txtsurgeon_KeyDown);
            this.txtthird_assistant.Leave += new EventHandler(this.txtsurgeon_Leave);
            this.txtthird_assistant.KeyPress += new KeyPressEventHandler(this.txtsurgeon_KeyPress);
            this.txtthird_assistant.Enter += new EventHandler(this.txtsurgeon_Enter);
            this.txtsecond_assistant.BackColor = Color.OldLace;
            this.txtsecond_assistant.Location = new Point(340, 130);
            this.txtsecond_assistant.Name = "txtsecond_assistant";
            this.txtsecond_assistant.Size = new Size(78, 21);
            this.txtsecond_assistant.TabIndex = 15;
            this.txtsecond_assistant.KeyDown += new KeyEventHandler(this.txtsurgeon_KeyDown);
            this.txtsecond_assistant.Leave += new EventHandler(this.txtsurgeon_Leave);
            this.txtsecond_assistant.KeyPress += new KeyPressEventHandler(this.txtsurgeon_KeyPress);
            this.txtsecond_assistant.Enter += new EventHandler(this.txtsurgeon_Enter);
            this.txtfirst_assistant.BackColor = Color.OldLace;
            this.txtfirst_assistant.Location = new Point(248, 130);
            this.txtfirst_assistant.MaxLength = 8;
            this.txtfirst_assistant.Name = "txtfirst_assistant";
            this.txtfirst_assistant.Size = new Size(90, 21);
            this.txtfirst_assistant.TabIndex = 14;
            this.txtfirst_assistant.TextChanged += new EventHandler(this.txtfirst_assistant_TextChanged);
            this.txtfirst_assistant.KeyDown += new KeyEventHandler(this.txtsurgeon1_KeyDown);
            this.txtfirst_assistant.Leave += new EventHandler(this.txtsurgeon_Leave);
            this.txtfirst_assistant.KeyPress += new KeyPressEventHandler(this.txtsurgeon1_KeyPress);
            this.txtfirst_assistant.Enter += new EventHandler(this.txtsurgeon_Enter);
            this.txtnotes_on_operation.Location = new Point(78, 209);
            this.txtnotes_on_operation.MaxLength = 20;
            this.txtnotes_on_operation.Name = "txtnotes_on_operation";
            this.txtnotes_on_operation.Size = new Size(321, 21);
            this.txtnotes_on_operation.TabIndex = 21;
            this.txtdiag_before_operation.BackColor = SystemColors.Window;
            this.txtdiag_before_operation.Location = new Point(71, 21);
            this.txtdiag_before_operation.MaxLength = 40;
            this.txtdiag_before_operation.Name = "txtdiag_before_operation";
            this.txtdiag_before_operation.Size = new Size(328, 21);
            this.txtdiag_before_operation.TabIndex = 4;
            this.txtpatient_condition.Location = new Point(452, 21);
            this.txtpatient_condition.MaxLength = 20;
            this.txtpatient_condition.Name = "txtpatient_condition";
            this.txtpatient_condition.Size = new Size(144, 21);
            this.txtpatient_condition.TabIndex = 5;
            this.txtOPERATING_DEPT.BackColor = Color.OldLace;
            this.txtOPERATING_DEPT.Location = new Point(492, 94);
            this.txtOPERATING_DEPT.Name = "txtOPERATING_DEPT";
            this.txtOPERATING_DEPT.Size = new Size(107, 21);
            this.txtOPERATING_DEPT.TabIndex = 12;
            this.txtOPERATING_DEPT.TextChanged += new EventHandler(this.txtOPERATING_DEPT_TextChanged);
            this.txtOPERATING_DEPT.KeyDown += new KeyEventHandler(this.txtOPERATING_DEPT_KeyDown);
            this.txtOPERATING_DEPT.Leave += new EventHandler(this.txtOPERATING_DEPT_Leave);
            this.txtOPERATING_DEPT.KeyPress += new KeyPressEventHandler(this.txtOPERATING_DEPT_KeyPress);
            this.txtOPERATING_DEPT.Enter += new EventHandler(this.txtOPERATING_DEPT_Enter);
            this.txtblood_tran_doctor.BackColor = SystemColors.Control;
            this.txtblood_tran_doctor.Location = new Point(80, 170);
            this.txtblood_tran_doctor.MaxLength = 8;
            this.txtblood_tran_doctor.Name = "txtblood_tran_doctor";
            this.txtblood_tran_doctor.ReadOnly = true;
            this.txtblood_tran_doctor.Size = new Size(104, 21);
            this.txtblood_tran_doctor.TabIndex = 18;
            this.txtsequence.Location = new Point(559, 60);
            this.txtsequence.MaxLength = 2;
            this.txtsequence.Name = "txtsequence";
            this.txtsequence.ReadOnly = true;
            this.txtsequence.Size = new Size(37, 21);
            this.txtsequence.TabIndex = 9;
            this.txtentered_by.Location = new Point(473, 209);
            this.txtentered_by.Name = "txtentered_by";
            this.txtentered_by.ReadOnly = true;
            this.txtentered_by.Size = new Size(123, 21);
            this.txtentered_by.TabIndex = 22;
            this.txtentered_by.KeyPress += new KeyPressEventHandler(this.txtsurgeon_KeyPress);
            this.txtsurgeon.BackColor = Color.OldLace;
            this.txtsurgeon.Location = new Point(80, 130);
            this.txtsurgeon.MaxLength = 8;
            this.txtsurgeon.Name = "txtsurgeon";
            this.txtsurgeon.Size = new Size(104, 21);
            this.txtsurgeon.TabIndex = 13;
            this.txtsurgeon.TextChanged += new EventHandler(this.txtsurgeon_TextChanged);
            this.txtsurgeon.KeyDown += new KeyEventHandler(this.txtsurgeon1_KeyDown);
            this.txtsurgeon.Leave += new EventHandler(this.txtsurgeon_Leave);
            this.txtsurgeon.KeyPress += new KeyPressEventHandler(this.txtsurgeon1_KeyPress);
            this.txtsurgeon.Enter += new EventHandler(this.txtsurgeon_Enter);
            this.cmboperating_room_no.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmboperating_room_no.Enabled = false;
            this.cmboperating_room_no.FormattingEnabled = true;
            this.cmboperating_room_no.Location = new Point(464, 59);
            this.cmboperating_room_no.Name = "cmboperating_room_no";
            this.cmboperating_room_no.Size = new Size(55, 20);
            this.cmboperating_room_no.TabIndex = 8;
            this.cmboperation_scale.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmboperation_scale.Enabled = false;
            this.cmboperation_scale.FormattingEnabled = true;
            this.cmboperation_scale.Items.AddRange(new object[]
			{
				"特",
				"大",
				"中",
				"小"
			});
            this.cmboperation_scale.Location = new Point(376, 94);
            this.cmboperation_scale.Name = "cmboperation_scale";
            this.cmboperation_scale.Size = new Size(48, 20);
            this.cmboperation_scale.TabIndex = 11;
            this.cmbanesthesia_method.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmbanesthesia_method.FormattingEnabled = true;
            this.cmbanesthesia_method.Location = new Point(239, 170);
            this.cmbanesthesia_method.Name = "cmbanesthesia_method";
            this.cmbanesthesia_method.Size = new Size(104, 20);
            this.cmbanesthesia_method.TabIndex = 19;
            this.cmbisolation_indicator.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmbisolation_indicator.FormattingEnabled = true;
            this.cmbisolation_indicator.Items.AddRange(new object[]
			{
				"正常",
				"隔离",
				"放射"
			});
            this.cmbisolation_indicator.Location = new Point(80, 95);
            this.cmbisolation_indicator.Name = "cmbisolation_indicator";
            this.cmbisolation_indicator.Size = new Size(61, 20);
            this.cmbisolation_indicator.TabIndex = 10;
            this.cmboperating_room.FormattingEnabled = true;
            this.cmboperating_room.Location = new Point(291, 59);
            this.cmboperating_room.Name = "cmboperating_room";
            this.cmboperating_room.Size = new Size(116, 20);
            this.cmboperating_room.TabIndex = 100;
            this.cmboperating_room.SelectedIndexChanged += new EventHandler(this.cmboperating_room_SelectedIndexChanged);
            this.dtpreq_date_time.CustomFormat = "yyyy-MM-dd HH:mm";
            this.dtpreq_date_time.Format = DateTimePickerFormat.Custom;
            this.dtpreq_date_time.Location = new Point(473, 170);
            this.dtpreq_date_time.Name = "dtpreq_date_time";
            this.dtpreq_date_time.Size = new Size(126, 21);
            this.dtpreq_date_time.TabIndex = 20;
            this.dtpreq_date_time.Visible = false;
            this.dtpscheduled_date_time.CustomFormat = "yyyy-MM-dd HH:mm";
            this.dtpscheduled_date_time.Format = DateTimePickerFormat.Custom;
            this.dtpscheduled_date_time.Location = new Point(107, 59);
            this.dtpscheduled_date_time.Name = "dtpscheduled_date_time";
            this.dtpscheduled_date_time.Size = new Size(126, 21);
            this.dtpscheduled_date_time.TabIndex = 6;
            this.label13.AutoSize = true;
            this.label13.Location = new Point(186, 174);
            this.label13.Name = "label13";
            this.label13.Size = new Size(53, 12);
            this.label13.TabIndex = 0;
            this.label13.Text = "麻醉方法";
            this.label12.AutoSize = true;
            this.label12.Location = new Point(16, 174);
            this.label12.Name = "label12";
            this.label12.Size = new Size(53, 12);
            this.label12.TabIndex = 0;
            this.label12.Text = "输血医师";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(528, 64);
            this.label6.Name = "label6";
            this.label6.Size = new Size(29, 12);
            this.label6.TabIndex = 0;
            this.label6.Text = "台次";
            this.label11.AutoSize = true;
            this.label11.Location = new Point(204, 134);
            this.label11.Name = "label11";
            this.label11.Size = new Size(29, 12);
            this.label11.TabIndex = 0;
            this.label11.Text = "助手";
            this.label8.AutoSize = true;
            this.label8.Location = new Point(303, 98);
            this.label8.Name = "label8";
            this.label8.Size = new Size(65, 12);
            this.label8.TabIndex = 0;
            this.label8.Text = "台手术等级";
            this.label10.AutoSize = true;
            this.label10.Location = new Point(16, 134);
            this.label10.Name = "label10";
            this.label10.Size = new Size(53, 12);
            this.label10.TabIndex = 0;
            this.label10.Text = "手术医师";
            this.label16.AutoSize = true;
            this.label16.Location = new Point(414, 213);
            this.label16.Name = "label16";
            this.label16.Size = new Size(53, 12);
            this.label16.TabIndex = 0;
            this.label16.Text = "申请医师";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(417, 63);
            this.label5.Name = "label5";
            this.label5.Size = new Size(41, 12);
            this.label5.TabIndex = 0;
            this.label5.Text = "手术间";
            this.label9.AutoSize = true;
            this.label9.Location = new Point(431, 98);
            this.label9.Name = "label9";
            this.label9.Size = new Size(53, 12);
            this.label9.TabIndex = 0;
            this.label9.Text = "手术科室";
            this.label17.AutoSize = true;
            this.label17.Location = new Point(153, 98);
            this.label17.Name = "label17";
            this.label17.Size = new Size(41, 12);
            this.label17.TabIndex = 0;
            this.label17.Text = "主诊组";
            this.label7.AutoSize = true;
            this.label7.Location = new Point(16, 98);
            this.label7.Name = "label7";
            this.label7.Size = new Size(53, 12);
            this.label7.TabIndex = 0;
            this.label7.Text = "隔离标志";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(417, 25);
            this.label2.Name = "label2";
            this.label2.Size = new Size(29, 12);
            this.label2.TabIndex = 0;
            this.label2.Text = "病情";
            this.label14.AutoSize = true;
            this.label14.Location = new Point(404, 174);
            this.label14.Name = "label14";
            this.label14.Size = new Size(53, 12);
            this.label14.TabIndex = 0;
            this.label14.Text = "申请时间";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(244, 63);
            this.label4.Name = "label4";
            this.label4.Size = new Size(41, 12);
            this.label4.TabIndex = 0;
            this.label4.Text = "手术室";
            this.label3.AutoSize = true;
            this.label3.Location = new Point(12, 63);
            this.label3.Name = "label3";
            this.label3.Size = new Size(89, 12);
            this.label3.TabIndex = 0;
            this.label3.Text = "手术日期及时间";
            this.label15.AutoSize = true;
            this.label15.Location = new Point(16, 213);
            this.label15.Name = "label15";
            this.label15.Size = new Size(47, 12);
            this.label15.TabIndex = 0;
            this.label15.Text = "备   注";
            this.label1.AutoSize = true;
            this.label1.Location = new Point(12, 25);
            this.label1.Name = "label1";
            this.label1.Size = new Size(53, 12);
            this.label1.TabIndex = 0;
            this.label1.Text = "术前诊断";
            this.sbtnAdd.Location = new Point(543, 63);
            this.sbtnAdd.Name = "sbtnAdd";
            this.sbtnAdd.Size = new Size(75, 23);
            this.sbtnAdd.TabIndex = 2;
            this.sbtnAdd.Text = "增加(&A)";
            this.sbtnAdd.Click += new EventHandler(this.sbtnAdd_Click);
            this.sbtnDelete.Location = new Point(543, 104);
            this.sbtnDelete.Name = "sbtnDelete";
            this.sbtnDelete.Size = new Size(75, 23);
            this.sbtnDelete.TabIndex = 2;
            this.sbtnDelete.Text = "删除(&D)";
            this.sbtnDelete.Click += new EventHandler(this.sbtnDelete_Click);
            this.panel2.AutoScroll = true;
            this.panel2.Controls.Add(this.gcOperaion);
            this.panel2.Dock = DockStyle.Top;
            this.panel2.Location = new Point(0, 45);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(655, 100);
            this.panel2.TabIndex = 1;
            this.gcOperaion.EmbeddedNavigator.Name = "";
            this.gcOperaion.Location = new Point(10, 0);
            this.gcOperaion.MainView = this.gvOperation;
            this.gcOperaion.Name = "gcOperaion";
            this.gcOperaion.Size = new Size(523, 100);
            this.gcOperaion.TabIndex = 0;
            this.gcOperaion.ViewCollection.AddRange(new BaseView[]
			{
				this.gvOperation
			});
            this.gcOperaion.Leave += new EventHandler(this.gcOperaion_Leave);
            this.gcOperaion.Enter += new EventHandler(this.gcOperaion_Enter);
            this.gvOperation.Columns.AddRange(new GridColumn[]
			{
				this.OPERATION,
				this.OPERATION_SCALE
			});
            this.gvOperation.GridControl = this.gcOperaion;
            this.gvOperation.Name = "gvOperation";
            this.gvOperation.OptionsView.ColumnAutoWidth = false;
            this.gvOperation.OptionsView.ShowGroupPanel = false;
            this.gvOperation.DoubleClick += new EventHandler(this.gvOperation_DoubleClick);
            this.gvOperation.ShownEditor += new EventHandler(this.gvOperation_ShownEditor);
            this.gvOperation.HiddenEditor += new EventHandler(this.gvOperation_HiddenEditor);
            this.OPERATION.Caption = "拟实施手术名称";
            this.OPERATION.FieldName = "OPERATION";
            this.OPERATION.Name = "OPERATION";
            this.OPERATION.OptionsColumn.AllowGroup = DefaultBoolean.False;
            this.OPERATION.OptionsColumn.AllowMove = false;
            this.OPERATION.OptionsColumn.AllowSort = DefaultBoolean.False;
            this.OPERATION.Visible = true;
            this.OPERATION.VisibleIndex = 0;
            this.OPERATION.Width = 406;
            this.OPERATION_SCALE.Caption = "等级";
            this.OPERATION_SCALE.FieldName = "OPERATION_SCALE";
            this.OPERATION_SCALE.Name = "OPERATION_SCALE";
            this.OPERATION_SCALE.OptionsColumn.AllowEdit = false;
            this.OPERATION_SCALE.OptionsColumn.AllowGroup = DefaultBoolean.False;
            this.OPERATION_SCALE.OptionsColumn.AllowMove = false;
            this.OPERATION_SCALE.OptionsColumn.AllowSort = DefaultBoolean.False;
            this.OPERATION_SCALE.OptionsColumn.ReadOnly = true;
            this.OPERATION_SCALE.Visible = true;
            this.OPERATION_SCALE.VisibleIndex = 1;
            this.OPERATION_SCALE.Width = 74;
            this.statusBottom.Items.AddRange(new ToolStripItem[]
			{
				this.tlstatusBottom
			});
            this.statusBottom.Location = new Point(0, 463);
            this.statusBottom.Name = "statusBottom";
            this.statusBottom.Size = new Size(655, 22);
            this.statusBottom.TabIndex = 4;
            this.statusBottom.Text = "Ready";
            this.tlstatusBottom.ForeColor = Color.Blue;
            this.tlstatusBottom.Name = "tlstatusBottom";
            this.tlstatusBottom.Size = new Size(35, 17);
            this.tlstatusBottom.Text = "Ready";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.ClientSize = new Size(655, 485);
            base.Controls.Add(this.statusBottom);
            base.Controls.Add(this.sbtnDelete);
            base.Controls.Add(this.sbtnAdd);
            base.Controls.Add(this.panel3);
            base.Controls.Add(this.panel2);
            base.Controls.Add(this.panel1);
            base.Name = "frmOperationConfirm";
            base.StartPosition = FormStartPosition.CenterParent;
            this.Text = "手术信息";
            base.Load += new EventHandler(this.frmOperationConfirm_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panelPYInput.ResumeLayout(false);
            this.panelPYInput.PerformLayout();
            ((ISupportInitialize)this.gridPYInput).EndInit();
            ((ISupportInitialize)this.gridViewPYInput).EndInit();
            this.panel3.ResumeLayout(false);
            this.panel3.PerformLayout();
            this.panel2.ResumeLayout(false);
            ((ISupportInitialize)this.gcOperaion).EndInit();
            ((ISupportInitialize)this.gvOperation).EndInit();
            this.statusBottom.ResumeLayout(false);
            this.statusBottom.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        #endregion
        private Panel panel1;
        private Label lblINP_NO;
        private Label lblPATIENT_ID;
        private Label lblName;
        private Panel panel3;
        private SimpleButton sbtnAdd;
        private SimpleButton sbtnDelete;
        private Label label2;
        private Label label1;
        private DateTimePicker dtpscheduled_date_time;
        private Label label3;
        private System.Windows.Forms.ComboBox cmboperating_room_no;
        private System.Windows.Forms.ComboBox cmboperation_scale;
        private System.Windows.Forms.ComboBox cmbisolation_indicator;
        private System.Windows.Forms.ComboBox cmboperating_room;
        private Label label12;
        private Label label6;
        private Label label11;
        private Label label8;
        private Label label10;
        private Label label5;
        private Label label9;
        private Label label7;
        private Label label4;
        private DateTimePicker dtpreq_date_time;
        private Label label13;
        private Label label14;
        private Label label16;
        private Label label15;
        private System.Windows.Forms.ComboBox cmbanesthesia_method;
        private Panel panel2;
        private GridControl gcOperaion;
        private GridView gvOperation;
        private GridColumn OPERATION;
        private GridColumn OPERATION_SCALE;
        private TextBox txtsurgeon;
        private TextBox txtfourth_assistant;
        private TextBox txtthird_assistant;
        private TextBox txtsecond_assistant;
        private TextBox txtfirst_assistant;
        private TextBox txtnotes_on_operation;
        private TextBox txtdiag_before_operation;
        private TextBox txtpatient_condition;
        private TextBox txtOPERATING_DEPT;
        private TextBox txtblood_tran_doctor;
        private TextBox txtsequence;
        private TextBox txtentered_by;
        private TextBox txtINP_NO;
        private TextBox txtPatID;
        private TextBox txtName;
        private StatusStrip statusBottom;
        private ToolStripStatusLabel tlstatusBottom;
        private Panel panelPYInput;
        private GridControl gridPYInput;
        private GridView gridViewPYInput;
        private GridColumn ITEM_NAME;
        private TextBox txtInPut;
        private Label lblPyItemName;
        private TextBox txtoperating_room;
        private SimpleButton simpleButton4;
        private SimpleButton sbtnSave;
        private TextBox txtpreq_date_time;
        private GridColumn OPERATION_SCALE１;
        private System.Windows.Forms.ComboBox cmbGroup;
        private Label label17;
    }
}